### ISSUE TITLE
Bug in `matches?` method.

### ISSUE THREAD

**Issue by Bartuz** [mongoid-rspec/mongoid-rspec#162]
I'm  testing model vs HABTM association
```
  1) Contact should reference and referenced in many "synced_emails" of type "BccEmail"
     Failure/Error: it { is_expected.to have_and_belong_to_many(:synced_emails).of_type('BccEmail') }
     NoMethodError:
       undefined method `sub' for BccEmail:Class
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/relations/metadata.rb:126:in `class_name'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/relations/metadata.rb:575:in `klass'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-rspec-2.1.0/lib/matchers/associations.rb:129:in `matches?'
     # ./spec/models/contact_spec.rb:4:in `block (2 levels) in <top (required)>'
```

and the same for of_type(Constant)

```
  1) Contact should reference and referenced in many "synced_emails" of type BccEmail
     Failure/Error: it { is_expected.to have_and_belong_to_many(:synced_emails).of_type(BccEmail) }
     NoMethodError:
       undefined method `sub' for BccEmail:Class
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/relations/metadata.rb:126:in `class_name'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/relations/metadata.rb:575:in `klass'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/mongoid-rspec-2.1.0/lib/matchers/associations.rb:129:in `matches?'
     # ./spec/models/contact_spec.rb:4:in `block (2 levels) in <top (required)>'
```

**Comment by Bartuz** [comment]
Sorry, it was my bad (I got a bit misled by error message). I haven't specified `:inverse_of` on `BccEmail`. Works like a charm now.
